Repository apache/logging-parent, pull requests merged in 2024-10, with the labels that each got.

#246 Extract Nexus URL using `nexus-staging-maven-plugin`
  .github/generate-email.sh
  .github/workflows/deploy-release-reusable.yaml
  pom.xml
  src/changelog/.11.x.x/change_nexus_deploy.xml
  src/site/antora/modules/ROOT/pages/release-instructions-project.adoc
Labels: enhancement, github_actions

#265 Change BOM activation and stop managing dependencies
  pom.xml
  src/changelog/.11.x.x/bom_activation.xml
  src/changelog/.11.x.x/bom_deps.xml
  src/changelog/.11.x.x/bom_parent.xml
Labels: bug, dependencies

#266 Adds `maven-args` option to workflows
  .github/workflows/build-reusable.yaml
  .github/workflows/merge-dependabot-reusable.yaml
  src/changelog/.11.x.x/maven-args.xml
Labels: enhancement

#269 Add verification step to release instructions
  src/site/antora/modules/ROOT/pages/release-instructions-project.adoc
Labels: documentation
